### ISSUE TITLE
Broken recording with ffmpeg

### ISSUE THREAD

**Issue by PurrSevere** [jrudess/streamdvr#137]
With all debugging options enabled, the error message I get is simply "-c: No such file or directory" in the $streamer.log output file. The terminal output repeats the same "not found in capturing directory, cannot convert to mp4" error message every second.

Streamlink records fine.

Versions:
streamdvr: 0.13.0
node: v12.1.0
ffmpeg: 4.1.3
streamlink: 1.1.1
youtube-dl: 2019.05.11

**Comment by jrudess** [comment]
I'm not able to replicate yet.   Can you post a sanitized config.yml and site.yml?

**Comment by jrudess** [comment]
I've pushed all my latest mods into master branch, just in case one of them happened to fix this without me realizing it.   Some of those mods do affect how 'paths' are built up as strings, and this error does seem path/file related.

**Comment by PurrSevere** [comment]
The latest commit did not fix this. I have tried on MacOS, Debian and even my docker container. Non of them work with the ffmpeg recording option. 

All I'm doing is downloading the latest source code, running `npm install`, adding a streamer that's online to test and then `node streamdvr`. 

From what I can tell, it looks like the URL is not being passed correctly to the script. If you manually type in the ffmpeg script and leave out the URL you can see that same error.

**Comment by PurrSevere** [comment]
I just pushed a new build of the container with today's changes in a new branch for testing. You can run it with `docker run purrsevere/streamdvr-docker:typescript`.  (Once it's done building on Docker Hub)

Maybe that will help figure out what's going on.

**Comment by jrudess** [comment]
I'm still on node v11.15.0.   Will test with v12 releases.

**Comment by jrudess** [comment]
Have reproduced the problem, looking into it.

**Comment by jrudess** [comment]
Does 38d3c896e5597edc31b78936b1c7591d0b0d5595 resolve it for you?

**Comment by PurrSevere** [comment]
That did it! Thanks!
